
CREATE TABLE if NOT EXISTS notificationtask (
    id BIGINT generated by default as identity primary key,
    chatid BIGINT not null,
    datetime TIMESTAMP not null,
    message CHARACTER VARYING(255) not null
)